spring:
  # ???????
  datasource:
    # ???????
    #    type: com.zaxxer.hikari.HikariDataSource
    # ????????????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123
  redis:
    host: 127.0.0.1
    port: 6379
    #password: admin
#redis??--jedis?
jedis:
  pool:
    #redis????IP
    host: localhost
    #redis????Port
    port: 6379
    #?????
    password:
    #??????
    timeout: 7200
    #???????
    maxTotall: 100
    #??????idel??????
    maxIdle: 100
    #??????idel??????
    minIdle: 50
    #?????????????????
    maxWaitMillis: 10000
    #???borrow Object?????????????
    testOnBorrow: true
    #???return Object?????????????
    testOnReturn: true
    #??????????????????????????????????????????-1.
    timeBetweenEvictionRunsMillis: 30000
    #?????????????????????????
    testWhileIdle: true
    # ???????????????????????????????3.
    numTestsPerEvictionRun: 50
